languageCode = "pl" 
languageName = "Polish"
weight = 1
title = "FUNDACJA<br>HOLISTIC SKIN"

[params]
  displayName = "PL"
  isoCode = "pl"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/logo.png"
  # secondaryLogo = "PATH"
  description = "holisticskin.org"
  # copyright = "&copy; 2023 Fundacja Holistic Skin"

[author]
  name = "Beata Rucka-Kańska"
  image = "img/bkanska.jpg"
  headline = "Fundacja Holistic Skin"
  bio = "Fundator Fundacji Holistic Skin. Spiritus Movens Sympozjum SKINLIVE<sup>&reg;</sup> we Wrocławiu."
  links = [
      { instagram = "https://instagram.com/kanskaeu" },
      { facebook = "https://facebook.com/wwwkanskaeu" },
      { link = "https://kanska.eu/" },
      { instagram = "https://instagram.com/sympozjumskinlive" },
      { facebook = "https://facebook.com/sympozjumskinlive" },
      { link = "https://skinlive.pl/" },
      { youtube = "https://www.youtube.com/@skinlive" },
      { instagram = "https://instagram.com/holisticskinorg" },
      { facebook = "https://facebook.com/holisticskinorg" },
      { link = "https://holisticskin.org/" },
  #   { email = "mailto:hello@your_domain.com" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { ko-fi = "https://ko-fi.com/username" },
  ]
